name: h_order_reception
description: H Order application.

version: 1.0.4+4

environment:
  sdk: ">=2.3.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1

  signalr_core: ^1.0.8

  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2

  json_annotation: ^3.1.1
  date_format: ^1.0.9
  intl: ^0.16.1

  sentry_flutter: ^4.0.6
  firebase_core: ^0.5.3
  firebase_messaging: ^7.0.3
  firebase_analytics: ^6.3.0
  firebase_crashlytics: ^0.2.4

  shared_preferences: ^0.5.12+4

  flutter_svg: ^0.19.1
  flutter_inner_drawer: ^0.5.8
  animated_text_kit: ^3.1.2
  fluttertoast: ^7.1.8
  flutter_local_notifications: ^4.0.1+2
  webview_flutter: ^1.0.7
  carousel_slider: ^3.0.0
  drag_and_drop_gridview: ^1.0.8
  timeline_tile: ^1.0.0
  date_picker_timeline: ^1.2.1

  device_info: ^1.0.0
  package_info: ^0.4.3+4
  battery: ^1.0.11
  wifi: ^0.1.5
  retrofit: ^1.3.4+1

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.9
  mobx_codegen: ^1.1.2
  json_serializable: ^3.5.1
  retrofit_generator: ^1.4.1+3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/common/
    - assets/icons/auth/
    - assets/icons/statusbar/
